# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maiwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

class Ui_FlashcardsPage(object):

    def setupUi(self, Widget):
    
        Widget.setObjectName("Widget")
        Widget.resize(724, 408)
        
        self.tblWidgetTopics = QtWidgets.QTableWidget(Widget)
        self.tblWidgetTopics.setGeometry(QtCore.QRect(60, 230, 650, 350))
        self.tblWidgetTopics.setObjectName("tblWidgetTopics")
        self.tblWidgetTopics.setColumnCount(3)
        self.tblWidgetTopics.setRowCount(1)
        self.tblWidgetTopics.setShowGrid(False)
        self.tblWidgetTopics.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tblWidgetTopics.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblWidgetTopics.horizontalHeader().setVisible(False)
        self.tblWidgetTopics.verticalHeader().setVisible(False)
        item = QtWidgets.QTableWidgetItem()
        self.tblWidgetTopics.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWidgetTopics.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWidgetTopics.setHorizontalHeaderItem(2, item)
        self.tblWidgetTopics.setColumnWidth(0,80)
        self.tblWidgetTopics.setColumnWidth(1,400)
        self.tblWidgetTopics.setColumnWidth(2,140)
        self.tblWidgetTopics.setStyleSheet("""
            QTableWidget::item {
                color: #f8f8f2;                    
                background-color: #44475a;
                margin-top: 2px;          
                border-radius: 0px;
                padding-left: 2px;
            }
            QTableWidget::item:hover {
                background-color: #6272a4;
                color : #f8f8f2;
            }
        """)

        self.lblDecks = QtWidgets.QLabel(Widget)
        self.lblDecks.setGeometry(QtCore.QRect(320, 200, 67, 18))
        self.lblDecks.setObjectName("lblDecks")
        self.lblClass = QtWidgets.QLabel(Widget)
        self.lblClass.setGeometry(QtCore.QRect(50, 130, 67, 18))
        self.lblClass.setObjectName("lblClass")

        self.listView = QtWidgets.QListView(Widget)
        self.listView.setGeometry(QtCore.QRect(100, 130, 81, 16))
        self.listView.setObjectName("listView")

        self.pushButton = QtWidgets.QPushButton(Widget)
        self.pushButton.setGeometry(QtCore.QRect(430, 130, 88, 26))
        self.pushButton.setObjectName("pushButton")

        self.btnAddCards = QtWidgets.QPushButton(Widget)
        self.btnAddCards.setGeometry(QtCore.QRect(530, 130, 88, 26))
        self.btnAddCards.setObjectName("btnAddCards")

        self.label = QtWidgets.QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 101))
        self.label.setStyleSheet(u"font-size : 24pt;\n"
"background : #44475a;\n"
"color:white;\n"
"border-radius:8px;")
        self.label.setAlignment(QtGui.Qt.AlignCenter)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", u"Flashcards"))
        
        item = self.tblWidgetTopics.horizontalHeaderItem(0)
        item.setText(_translate("Widget", u"hints_percentage"))
        item = self.tblWidgetTopics.horizontalHeaderItem(1)
        item.setText(_translate("Widget", u"deck_name"))
        item = self.tblWidgetTopics.horizontalHeaderItem(2)
        item.setText(_translate("Widget", u"btn_action"))
        
        self.lblDecks.setText(_translate("Widget", u"Decks"))
        self.lblClass.setText(_translate("Widget", u"Class:"))
        self.pushButton.setText(_translate("Widget", u"More Info"))
        self.btnAddCards.setText(_translate("Widget", u"Add Cards"))

        self.label.setText(_translate("Widget", u"Flashcards"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_FlashcardsPage()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
