# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_dailytask_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_DailyTaskPage(object):
    def setupUi(self, DailyTaskPage):
        DailyTaskPage.setObjectName("DailyTaskPage")
        DailyTaskPage.resize(800, 600)
        DailyTaskPage.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(DailyTaskPage)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(DailyTaskPage)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnOrderByType = QtWidgets.QPushButton(self.frame_3)
        self.btnOrderByType.setMinimumSize(QtCore.QSize(100, 40))
        self.btnOrderByType.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnOrderByType.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOrderByType.setAutoFillBackground(False)
        self.btnOrderByType.setStyleSheet("background-repeat: no-repeat; \n"
"border-radius: 20px;\n"
"text-align: center;\n"
"font-size: 12px;")
        self.btnOrderByType.setObjectName("btnOrderByType")
        self.horizontalLayout_2.addWidget(self.btnOrderByType)
        self.btnOrderByStatus = QtWidgets.QPushButton(self.frame_3)
        self.btnOrderByStatus.setMinimumSize(QtCore.QSize(100, 40))
        self.btnOrderByStatus.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnOrderByStatus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOrderByStatus.setAutoFillBackground(False)
        self.btnOrderByStatus.setStyleSheet("background-repeat: no-repeat; \n"
"border-radius: 20px;\n"
"text-align: center;\n"
"font-size: 12px;")
        self.btnOrderByStatus.setObjectName("btnOrderByStatus")
        self.horizontalLayout_2.addWidget(self.btnOrderByStatus, 0, QtCore.Qt.AlignLeft)
        self.btnOrderByDate = QtWidgets.QPushButton(self.frame_3)
        self.btnOrderByDate.setMinimumSize(QtCore.QSize(100, 40))
        self.btnOrderByDate.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnOrderByDate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOrderByDate.setAutoFillBackground(False)
        self.btnOrderByDate.setStyleSheet("background-repeat: no-repeat; \n"
"border-radius: 20px;\n"
"text-align: center;\n"
"font-size: 12px;")
        self.btnOrderByDate.setObjectName("btnOrderByDate")
        self.horizontalLayout_2.addWidget(self.btnOrderByDate, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignLeft)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(DailyTaskPage)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("font: bold 20px;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.tblTasks = QtWidgets.QTableWidget(self.frame_2)
        self.tblTasks.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tblTasks.setStyleSheet("")
        self.tblTasks.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tblTasks.setShowGrid(False)
        self.tblTasks.setObjectName("tblTasks")
        self.tblTasks.setColumnCount(6)
        self.tblTasks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblTasks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTasks.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTasks.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTasks.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTasks.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTasks.setHorizontalHeaderItem(5, item)
        self.tblTasks.horizontalHeader().setHighlightSections(False)
        self.tblTasks.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tblTasks)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(DailyTaskPage)
        QtCore.QMetaObject.connectSlotsByName(DailyTaskPage)

    def retranslateUi(self, DailyTaskPage):
        _translate = QtCore.QCoreApplication.translate
        DailyTaskPage.setWindowTitle(_translate("DailyTaskPage", "Widget"))
        self.btnOrderByType.setText(_translate("DailyTaskPage", "Tipo"))
        self.btnOrderByStatus.setText(_translate("DailyTaskPage", "Status"))
        self.btnOrderByDate.setText(_translate("DailyTaskPage", "Data"))
        self.label.setText(_translate("DailyTaskPage", "Tasks"))
        item = self.tblTasks.horizontalHeaderItem(0)
        item.setText(_translate("DailyTaskPage", "Nome"))
        item = self.tblTasks.horizontalHeaderItem(1)
        item.setText(_translate("DailyTaskPage", "Status"))
        item = self.tblTasks.horizontalHeaderItem(2)
        item.setText(_translate("DailyTaskPage", "Data Inicial"))
        item = self.tblTasks.horizontalHeaderItem(3)
        item.setText(_translate("DailyTaskPage", "Data Final"))
        item = self.tblTasks.horizontalHeaderItem(4)
        item.setText(_translate("DailyTaskPage", "Tópico"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DailyTaskPage = QtWidgets.QWidget()
    ui = Ui_DailyTaskPage()
    ui.setupUi(DailyTaskPage)
    DailyTaskPage.show()
    sys.exit(app.exec_())
