# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_cards_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_addCardsWindow(object):
    def setupUi(self, addCardsWindow):
        addCardsWindow.setObjectName("addCardsWindow")
        addCardsWindow.setWindowModality(QtCore.Qt.WindowModal)
        addCardsWindow.resize(500, 250)
        addCardsWindow.setAutoFillBackground(False)
        addCardsWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(addCardsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblDeckName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.lblDeckName.setFont(font)
        self.lblDeckName.setStyleSheet("font: bold 15px;")
        self.lblDeckName.setObjectName("lblDeckName")
        self.verticalLayout_3.addWidget(self.lblDeckName)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEditFront = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEditFront.setObjectName("plainTextEditFront")
        self.verticalLayout.addWidget(self.plainTextEditFront)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.plainTextEditVerse = QtWidgets.QPlainTextEdit(self.frame_2)
        self.plainTextEditVerse.setObjectName("plainTextEditVerse")
        self.verticalLayout_2.addWidget(self.plainTextEditVerse)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAddCardInDeck = QtWidgets.QPushButton(self.frame_4)
        self.btnAddCardInDeck.setObjectName("btnAddCardInDeck")
        self.horizontalLayout_2.addWidget(self.btnAddCardInDeck)
        self.verticalLayout_3.addWidget(self.frame_4)
        addCardsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(addCardsWindow)
        QtCore.QMetaObject.connectSlotsByName(addCardsWindow)

    def retranslateUi(self, addCardsWindow):
        _translate = QtCore.QCoreApplication.translate
        addCardsWindow.setWindowTitle(_translate("addCardsWindow", "addCardsWindow"))
        self.lblDeckName.setText(_translate("addCardsWindow", "DeckName"))
        self.label.setText(_translate("addCardsWindow", "Frente (pergunta)"))
        self.label_2.setText(_translate("addCardsWindow", "Verso (resposta)"))
        self.btnAddCardInDeck.setText(_translate("addCardsWindow", "Adicionar Card"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addCardsWindow = QtWidgets.QMainWindow()
    ui = Ui_addCardsWindow()
    ui.setupUi(addCardsWindow)
    addCardsWindow.show()
    sys.exit(app.exec_())
